config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :posts, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    attr_accessor :remember_token
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    def forget
      update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        redirect_to posts_path
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :new]
  
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params) 
    @post.user_id = @current_user.id
    if @post.save
      redirect_to posts_path
    end
  end
  
  def index
    @posts = Post.all
  end
  
  private
  
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          log_in user
          remember user
          redirect_to posts_path
        else
          render new_session_path
        end
    end
    
    def destroy
        log_out
        redirect_to posts_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end
    
    def logged_in?
      !current_user.nil?
    end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>These are all your posts.</h1>

<% @posts.each do |post| %>
    <p>Content:  <%= post.content %> </p>
    <% if logged_in? %>
   <p>User ID: <%= post.user_id %> </p>
   <%end%>
   <p>--------</p>
   
<%end%>

<p>*****************</p>

<% if logged_in? %>
    <%= link_to "Sign out", session_path(current_user), method: :delete %>
    <%= link_to "New Post", new_post_path %>
<%else%>
    <%= link_to "Sign in to see author", new_session_path %>
<%end%>

app/views/posts/new.html.erb
<%=form_for @post do |f| %>
<%= f.label :content %>
<%= f.text_area :content %>

<%=f.submit "Make post"%>

<%end%>